version: "3.3"
services:
    mariadb-glpi: 
        image: fametec/glpi:9.5.2-mariadb
        restart: unless-stopped
        volumes:
          - mariadb-glpi-volume:/var/lib/mysql:rw
        environment: 
          MYSQL_DATABASE: glpi
          MYSQL_USER: glpi-user 
          MYSQL_PASSWORD: glpi-pass 
          MYSQL_RANDOM_ROOT_PASSWORD: 1 
          #        ports:
          #- 3306:3306
        networks: 
          - glpi-backend
#
#
    glpi: 
        image: fametec/glpi:9.5.2-nginx
        restart: unless-stopped
        volumes:
          - glpi-volume-files:/usr/share/nginx/html/glpi/files:rw
          - glpi-volume-plugins:/usr/share/nginx/html/glpi/plugins:rw
        depends_on: 
          - mariadb-glpi
          - php-fpm
        ports: 
          - 80:80
        networks: 
          - glpi-frontend
          - glpi-backend

    php-fpm: 
        image: fametec/glpi:9.5.2-php-fpm
        restart: unless-stopped
        volumes:
          - glpi-volume-files:/usr/share/nginx/html/glpi/files:rw
          - glpi-volume-plugins:/usr/share/nginx/html/glpi/plugins:rw
        depends_on:
          - mariadb-glpi
        networks:
          - glpi-backend
#        ports:
#          - 9000:9000
#
    # cron:
    #     image: fametec/glpi-cron-php-fpm:latest
    #     restart: unless-stopped
    #     volumes:
    #       - glpi-volume-files:/usr/share/nginx/html/glpi/files:rw
    #       - glpi-volume-plugins:/usr/share/nginx/html/glpi/plugins:rw
    #     depends_on:
    #       - mariadb-glpi
    #     networks:
    #       - glpi-backend
#
networks: 
    glpi-frontend: 
    glpi-backend:
#
volumes:
    glpi-volume-files:
    glpi-volume-plugins:
    mariadb-glpi-volume:
