version: "3.3"
services:
    mariadb-glpi: 
        image: fametec/glpi:9.5.5-mariadb
        restart: unless-stopped
        volumes: 
          - mariadb-glpi-volume:/var/lib/mysql:rw
        environment: 
          MYSQL_DATABASE: glpi
          MYSQL_USER: glpi-user 
          MYSQL_PASSWORD: glpi-pass 
          MYSQL_RANDOM_ROOT_PASSWORD: 1 
        ports: 
          - 3306:3306
        networks: 
          - glpi-backend
#
#
    glpi: 
        image: fametec/glpi:9.5.5
        restart: unless-stopped
        volumes: 
          - glpi-volume-files:/var/www/html/files:rw
          - glpi-volume-plugins:/var/www/html/plugins:rw
        environment: 
          GLPI_LANG: pt_BR
          MARIADB_HOST: mariadb-glpi
          MARIADB_PORT: 3306
          MARIADB_DATABASE: glpi
          MARIADB_USER: glpi-user
          MARIADB_PASSWORD: glpi-pass
          VERSION: "9.5.5"
          PLUGINS: "all"
        depends_on: 
          - mariadb-glpi
        ports: 
          - 80:80
        networks: 
          - glpi-frontend
          - glpi-backend
#
# CRON
#
    crond: 
        image: fametec/glpi:9.5.5-crond
        restart: unless-stopped
        depends_on:
          - mariadb-glpi
        environment: 
          MARIADB_HOST: mariadb-glpi
          MARIADB_PORT: 3306
          MARIADB_DATABASE: glpi
          MARIADB_USER: glpi-user
          MARIADB_PASSWORD: glpi-pass
        volumes: 
          - glpi-volume-files:/var/www/html/files:rw
          - glpi-volume-plugins:/var/www/html/plugins:rw
        networks: 
          - glpi-backend
#
# VOLUMES
#
volumes: 
  glpi-volume-files:
  glpi-volume-plugins:
  mariadb-glpi-volume: 
#
# NETWORKS
#
networks: 
    glpi-frontend: 
    glpi-backend:
